# calculate the probability of a point along a density curve that 
# was generated by kernel density estimation 

# https://stats.stackexchange.com/questions/78711/how-to-find-estimate-probability-density-function-from-density-function-in-r

df <- approxfun(density(dat_pop))
plot(density(dat_pop))
xnew <- mean(dat_pop)
points(xnew, df(xnew), col=2)

df(mean(dat_pop))
df(d_mode(dat_pop))
